using System;
using System.IO;
using System.Text;
using EverlastingEditor.Base;

namespace EverlastingEditor.Config.Export
{
    public class Loader
    {
        public string[] ConfigNames { get; }
        protected string CsOutputPath { get; }
        
        public Loader(string[] configNames, string csOutputPath)
        {
            Array.Sort(configNames);
            this.ConfigNames = configNames;
            this.CsOutputPath = csOutputPath;
        }

        public void Export()
        {
            using (var sb = new AutoIndentedTextWriter())
            {
                WriteCsTemplate(sb);
                FileInfo fi = new FileInfo($"{CsOutputPath}/TableDataManager.cs");
                fi.Directory.Create();
                File.WriteAllText(fi.FullName, sb.ToString(), Encoding.UTF8);
            }
        }
        
        private void WriteCsTemplate(IndentedTextWriter sw)
        {
            sw.WriteLine("//------------------------------------------------------------------------------");
            sw.WriteLine("// <auto-generated>");
            sw.WriteLine("//     This code was generated by a tool.");
            sw.WriteLine("//");
            sw.WriteLine("//     Changes to this file may cause incorrect behavior and will be lost if");
            sw.WriteLine("//     the code is regenerated.");
            sw.WriteLine("// </auto-generated>");
            sw.WriteLine("//------------------------------------------------------------------------------");
            
            sw.WriteLine("using System.Collections.Generic;");
            sw.WriteLine("using Cysharp.Threading.Tasks;");
            sw.WriteLine("namespace Everlasting.Config");
            sw.WriteLine("{");

            sw.WriteLine("public static class TableDataManager");
            sw.WriteLine("{");

            sw.WriteLine("public static async UniTask Load()");
            sw.WriteLine("{");

            sw.WriteLine("IEnumerable<UniTask> LoadAll()");
            sw.WriteLine("{");
            
            foreach (var name in ConfigNames)
            {
                sw.WriteLine($"yield return Internal.{name}TableLoader.Load();");
            }
            
            sw.WriteLine("}");
            
            sw.WriteLine("await UniTask.WhenAll(LoadAll());");
            sw.WriteLine("}");

            sw.WriteLine("");
            sw.WriteLine("public static void Clear()");
            sw.WriteLine("{");

            foreach (var name in ConfigNames)
            {
                sw.WriteLine($"Internal.{name}TableLoader.Clear();");
            }

            sw.WriteLine("}");

            sw.WriteLine("}");

            sw.WriteLine("}");
        }
    }
}